parameters:
  executableName: ""
  archiveFile: ""
  archiveType: ""
  linux: false
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: "x64"
    displayName: "Install Python"
  - bash: |
      rustup update
    displayName: "Install latest Rust version"
  - ${{ if eq(parameters.linux, 'false') }}:
      - bash: |
          export RUST_BACKTRACE=1
          cargo test --all --locked
        displayName: "Run tests"
  - ${{ if eq(parameters.linux, 'true') }}:
      - bash: |
          export RUSTUP_TOOLCHAIN="nightly-2020-02-06"
          cargo install grcov
          export CARGO_INCREMENTAL=0
          export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
          export RUST_BACKTRACE=1
          cargo test --all --locked
        displayName: "Run tests with coverage"
      - script: python -m pip install --upgrade pip setuptools wheel
        displayName: "Install Python tools"
      - bash: |
          zip -0 ccov.zip `find . \( -name "texlab*.gc*" -o -name "deps*build*.gc*" \) -print`;
          grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "{/*,target/*}" -o lcov.info
          python -m pip install lcov_cobertura
          python -m lcov_cobertura lcov.info
        displayName: "Build coverage report"
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: cobertura
          summaryFileLocation: "coverage.xml"
        displayName: "Publish coverage report"
  - ${{ if contains(variables['Build.SourceBranch'], 'tags') }}:
      - bash: |
          cargo build --release --locked
        displayName: "Build release artifact"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "target/release/${{ parameters.executableName }}"
          archiveType: ${{ parameters.archiveType }}
          tarCompression: "gz"
          archiveFile: "$(Build.ArtifactStagingDirectory)/${{ parameters.archiveFile }}"
        displayName: "Compress release artifact"
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: ${{ parameters.archiveFile }}
        displayName: "Publish release artifact"
